name: build go
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v -o myapp.linux ./cmd
      - name: Test with the Go CLI
        run: go test ./...
      - name: show
        run: tree .
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp.linux
          path: myapp.linux
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')  # Only run on tag push
        uses: ncipollo/release-action@v1
        with:
          artifacts: myapp.linux
          body: "Release ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}