name: nginx static container build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#single-cpu-runners
      matrix:
        os:
          - ubuntu-26.04
          - ubuntu-26.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v7

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: show env and secrets
        run: |
          echo ${{ vars.A }}
          echo ${{ secrets.S }}

      # https://github.com/docker/login-action
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-variables
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v4
      #  with:
      #    registry: docker.io
      #    username: ${{ vars.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}