name: nginx static container build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-26.04
          - ubuntu-26.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v5

      - name: show os-release
        run: cat /etc/os-release

      - name: show mem
        run: free -h

      - name: show cpu
        run: lscpu

      - name: show arch
        run: uname -a

      - name: show matrix.runner
        run: echo ${{ matrix.runner }}