name: nginx static container build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#single-cpu-runners
      matrix:
        os:
          - ubuntu-26.04
          - ubuntu-26.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Run am64/amd64 container
        run: docker run --rm alpine uname -m