name: openresty dynamic container build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: test-openresty
  ALPINE_IMAGE: alpine:3.24.1
  RESTY_VERSION: 1.31.1.1

permissions:
  contents: read

jobs:
  build_docker:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-26.04
            platform: linux/amd64
            arch: amd64

          - os: ubuntu-26.04-arm
            platform: linux/arm64
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v7
        with:
          context: openresty/static
          file: openresty/static/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            ALPINE_IMAGE=${{ env.ALPINE_IMAGE }}
            RESTY_VERSION=${{ env.RESTY_VERSION }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-26.04

    needs:
      - build_docker

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"

          docker buildx imagetools create \
            -t "${IMAGE}:${{ env.RESTY_VERSION }}-dynamic" \
            $(printf "${IMAGE}@sha256:%s " *)

      - name: Inspect image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"

          docker buildx imagetools inspect "${IMAGE}:${{ env.RESTY_VERSION }}-dynamic"